### ISSUE TITLE
Mismatched Resource file

### ISSUE THREAD

**Issue by H3ADROOM** [DrAbcOfficial/ABCEnchance#10]
https://imgur.com/a/z6oS4Zr
I had installed ABCEnchance correctly.

**Comment by DrAbcOfficial** [comment]
obviously you haven't installed it correctly. Because of program can not load res file.
Please ensure your file installed like this.
```
Sven Coop
├─svencoop
│  └─abcenchance
│     ├─localize
│     ├─mdl
│     ├─shader
│     ├─spr
│     ├─tga
│     ABCEnchance.res
svencoop.exe
```

**Comment by H3ADROOM** [comment]
> r

https://imgur.com/a/97amTFL
