### ISSUE TITLE
Choose weapon also shoot 

### ISSUE THREAD

**Issue by SonThanhVN** [DrAbcOfficial/ABCEnchance#14]
when selecting a weapon with a gun in your hand
the gun will shoot a bullet before change to the item that you are selecting
https://imgur.com/a/rMbQpmL

**Comment by longlong2002** [comment]
Plus does not allow +attack to select weapons and Func_tank refuses goes to work

**Comment by DrAbcOfficial** [comment]
fix in af4b04e
