### ISSUE TITLE
Compatibility: Servers with buy menu (specifically money count)

### ISSUE THREAD

**Issue by RavenMacDaddy** [DrAbcOfficial/ABCEnchance#15]
See the following screenshot where the money count is overlapping the HUD:

![image](https://user-images.githubusercontent.com/67732686/192036887-fb6f79ff-ba7b-4707-b207-732e2f82cfc6.png)

**Comment by DrAbcOfficial** [comment]
This icon is controlled by the server administrator, the exact position depends on your own resolution, please contact the server administrator to change the buy menu configuration. or change the value of the ·"HealthArmor.BackGroundY"· item in the ·svencoop/abcenchance/ABCEnchance.res· file, e.g: "HealthArmor.BackGroundY"		"0.97"

**Comment by RavenMacDaddy** [comment]
Got it, thanks @DrAbcOfficial
