### ISSUE TITLE
Compatibility: HUD_fastswitch CVAR

### ISSUE THREAD

**Issue by RavenMacDaddy** [DrAbcOfficial/ABCEnchance#16]
Having HUD_fastswitch enabled combined with using the mod, the weapon menu still shows up when switching weapons – e.g., mouse wheel up/down.

This means that when the user presses Fire (e.g., mouse button 1), they'll instead switch weapon – again – when they intend to fire their weapon.

**Comment by DrAbcOfficial** [comment]
fix in bd3d53b
