### ISSUE TITLE
Compatibility: MetaHookSv Advanced video settings menu (AVX2)

### ISSUE THREAD

**Issue by RavenMacDaddy** [DrAbcOfficial/ABCEnchance#17]
With ABCEnhance loaded, it looks like this:

![image](https://user-images.githubusercontent.com/67732686/192039163-0ca24f48-c2cd-487f-a79f-b197f69ee511.png)

If I do not load it, it looks normal, like this:

![image](https://user-images.githubusercontent.com/67732686/192039281-3f8ca274-e973-45cc-abd0-daa0689242d9.png)

For reference, my system is using the AVX2 plugins.

**Comment by DrAbcOfficial** [comment]
fixed in 5a9af22
