### ISSUE TITLE
Scoreboard Problem on TWLZ server

### ISSUE THREAD

**Issue by svcino** [DrAbcOfficial/ABCEnchance#18]
![20221023103142_1](https://user-images.githubusercontent.com/33147204/197371061-148c254e-13c5-411e-87d0-eb938ca70ece.jpg)
can fix these issue?

**Comment by svcino** [comment]
That happened back When ABCex got an New scoreboard feature.
Step to Reproduce:
Step 1. Join TWLZ server
Step 2. Wait 
Step 3. Gone, Scoreboard Become Blank

**Comment by DrAbcOfficial** [comment]
看不懂

**Comment by ClifffordW** [comment]
> 看不懂

當 ABCex 獲得新的記分板功能時，這種情況就發生了。
 重現步驟：
 第一步，加入TWLZ服務器
 步驟 2. 等待
 第 3 步。走了，記分牌變成空白
