### ISSUE TITLE
[BUG]使用滚轮进行切换武器操作时，无法跳过空的武器大类

### ISSUE THREAD

**Issue by 7UMENGL1aNG** [DrAbcOfficial/ABCEnchance#19]
**背景：**
拥有武器：撬棍、手枪、狙击枪
滚轮使用：只用滚轮下（但实际上滚轮上效果一样，但是在此处是为了控制变量）

**具体流程及对比：**
分支一：
按下数字键1（指选定目标武器大类，通常1为近战组）后，使用滚轮。
原版进行滚轮切换时，可以用滚轮从撬棍切换到手枪、再从手枪切换到狙击枪。
安装该插件后(保证cl_hud_csgo 1)，可以用滚轮切换至手枪，但无法从手枪切换到狙击枪。
分支二：
不按下数字键1，直接使用滚轮。
则无论手持什么武器都会从撬棍开始选起。
继续使用滚轮，原版可以从撬棍切换至手枪，从手枪切换至狙击枪。
使用插件后，无法从手枪切换至狙击枪。

**结论：**
当cl_hud_csgo 1时，滚轮切换时无法跳过空的武器类（没有冲锋枪之类的话就没法用滚轮切换到狙击枪了）

**Comment by DrAbcOfficial** [comment]
淦，这比想象的还难修，正在推倒重新写这部分
还要点时间

**Comment by DrAbcOfficial** [comment]
10c2f64

**Comment by 7UMENGL1aNG** [comment]
> [10c2f64](https://github.com/DrAbcOfficial/ABCEnchance/commit/10c2f647d45c0a378547bd9d77f3ee4850a9c0a4)

当武器栏位中没有撬棍时，滚轮切换武器似乎有BUG。
比如说：
撬棍被扔掉了，或者出生就没携带。
当手持武器为扳手时，依然无法使用滚轮进进行切换
同理，手持武器为遥控炸弹时，无法使用滚轮切换。

**Comment by DrAbcOfficial** [comment]
用最新的release了么

**Comment by 7UMENGL1aNG** [comment]
> 用最新的release了么

应该是没用最新版本的原因，现在我重新安装之后似乎已经没问题了。

那我刚刚汇报的信息应该是属于过期信息了。
