### ISSUE TITLE
CVar to hide $ in csgo hud

### ISSUE THREAD

**Issue by incognico** [DrAbcOfficial/ABCEnchance#2]
A CVar to hide $ (money) in the csgo hud.

Or maybe enable eccocheck by default and only show it when ecco was detected.

**Comment by DrAbcOfficial** [comment]
added this cvar in 27c8794e5de9f81da7e5a7adba92a0e9274838f8
now you can   enable it via `cl_eccoenable` 0(off)/1(always show)/2(only detected ecco plugin)
