### ISSUE TITLE
[BUG]物品发光范围疑似失效

### ISSUE THREAD

**Issue by 7UMENGL1aNG** [DrAbcOfficial/ABCEnchance#21]
### 确保cl_hud_csgo 1，且cl_itemhighlight 1
`另外进行了自定义调整，但应该不会影响cl_wmenustyle 0；cl_hud_healthammo_style 0；cl_radar 0；cl_crosshair 0；cl_eccoenable 0`
### 运行插件：
```
ABCEnchance.dll
CaptionMod.dll
Renderer.dll
BulletPhysics.dll
StudioEvents.dll
CommunicationDemo.dll
SCModelDownloader.dll
SteamScreenshots.dll
```
---
### 测试环境分支一：
服务器：Null服-RPG
地图：sc_titans
测试方式：
自然生成的武器并没有框，`通过/buy购买的`自定义武器没有框，`通过/buy购买的`原版SvenCoop的武器没有框，`通过/buy购买的`弹药没有框。

### 测试环境分支二：
服务器：本地服务器
地图：hl_c02_a2
测试方式：
寻找自然生成的物品，升降机前巴尼尸体周围的两个弹药没有框。

###  测试环境分支三：
服务器：贴吧服（注意头蟹）
地图：sc_egypt2
测试方式：
自然生成的武器并没有框，自然生成的弹药没有框，`通过/buy购买的`自定义武器没有框，`通过/buy购买的`原版SvenCoop的武器没有框，`通过/buy购买的`弹药没有框。

###  测试环境分支四：
服务器：Null服-真伤服
地图：leprechaun2
测试方式：
自然生成的医疗包和弹药没有框，`通过/buy购买的'各种武器和弹药没有框。

---

经过上述测试，判定物品发光失效。
推测应该和metahook的更新有关，还请检查。（因为在不久前，我还能通过购买多余的武器的方式看到发光框；虽说只要离远'丢失发光框'就算再靠近也看不见）

**Comment by 7UMENGL1aNG** [comment]
顺带一提，我顺便帮忙测试了ecco显示，ecco显示在Null服和贴吧服均失效。
运行环境大概是cl_eccoenable1；cl_eccocheck 1；cl_eccocmenu 1（这里和两个README中的cl_eccobuymenu不一样，需要择期更改）
不过这一点我没有退出游戏重进，不知道会不会影响。

**Comment by 7UMENGL1aNG** [comment]
破案了 其中大部分居然是Metahook的问题。

**Comment by 7UMENGL1aNG** [comment]
不过仍然有一些问题：
自然生成的原版武器看起来没有问题
其中通过/buy购买的SvenCoop原版弹药和武器买出来后会带有发光(只不过在Null服买的医疗包显示是黄色)，远离后再靠近就不会有了'Null服和贴吧服都是如此'
自定义武器没有发光范围'Null服和贴吧服都是如此'

**Comment by DrAbcOfficial** [comment]
自定义武器发光要自己在 abcenchance/ItemHighLightList.txt里添加模型路径，0是物品，1是子弹，2是武器
我不可能为每个服务器都添加默认支持，这个需要你自己添加

> 不过仍然有一些问题： 自然生成的原版武器看起来没有问题 其中通过/buy购买的SvenCoop原版弹药和武器买出来后会带有发光(只不过在Null服买的医疗包显示是黄色)，远离后再靠近就不会有了'Null服和贴吧服都是如此'

自定义武器没有发光范围'Null服和贴吧服都是如此'

**Comment by DrAbcOfficial** [comment]
> 顺带一提，我顺便帮忙测试了ecco显示，ecco显示在Null服和贴吧服均失效。 运行环境大概是cl_eccoenable1；cl_eccocheck 1；cl_eccocmenu 1（注意：这里和两个README中的cl_eccobuymenu不一样，需要择期更改） 不过这一点我没有退出游戏重进，不知道会不会影响。
> 
> 在以上参数执行后，退出游戏重进cl_eccocheck会自动归零，不清楚什么情况。

这个参数需要服务器有插件扩展支持，现在两个服务器都没有安装扩展

**Comment by 7UMENGL1aNG** [comment]
那我想应该没什么问题了
