### ISSUE TITLE
[BugAndSuggestion]一些无伤大雅的问题

### ISSUE THREAD

**Issue by 7UMENGL1aNG** [DrAbcOfficial/ABCEnchance#22]
### 无伤大雅的原因：在不使用目标功能时才会出错，而大部分人选择这个插件也是因为有那个功能。

---

### 一、准心
动态准心开启`cl_crosshair 1`的时候，将cl_hud_csgo调整为0会导致游戏自带的准心消失。
动态准心关闭后，cl_hud_csgo 0时不会导致原来的准心消失。

### 二、死亡提示
在另外做了一个死亡提示后，大概是为了避免雷达的干扰，又或是用时出现两个死亡提示过于累赘，所以将原游戏的死亡提示关闭了，这很好。
但cl_hud_csgo 0时，原游戏的死亡提示也不会出现，这令人难过。
推荐：再做一个死亡提示的开关，默认关闭即可。

还有个Echo问题，这个在[[BUG]物品发光范围疑似失效 #21](https://github.com/DrAbcOfficial/ABCEnchance/issues/21#issuecomment-1417937097)已进行阐述，不再重复。

---

总之是个相当优秀的模组，另外要是这个血条长度能够再匹配一些就更好了（我猜测是因为没有添加底纹，所以没有对照物，会感觉血条长度和实际血量大小不一样）

**Comment by 7UMENGL1aNG** [comment]
### SC因你们这些人的奉献而精彩 ♥

**Comment by DrAbcOfficial** [comment]
准心，死亡信息，血条显示，雷达，投票，高光，购买菜单，手雷指示器现在不受总开关的影响
血条长度是opengl的问题，等到有时间有心情用VGUI重写
f3f7099 里改了，可以在action里找到

**Comment by DrAbcOfficial** [comment]
Echo问题建议联系服主
