### ISSUE TITLE
[Suggestion] Check if FOV is below a certain value before applying viewmodellag

### ISSUE THREAD

**Issue by marvinmods** [DrAbcOfficial/ABCEnchance#23]
Custom weapons which have a iron sight feature becomes displaced when moving the camera around.
How to reproduce, use [KernCore's Insurgency Weapon Pack](https://github.com/KernCore91/-SC-Insurgency-Weapons-Project)
Video evidence:
[![modellagtest](https://img.youtube.com/vi/dQAj-8UsUrA/maxresdefault.jpg)](https://youtu.be/dQAj-8UsUrA)

Suggestion: Implement a check that sees if FOV is below a certain value (cl_ cvar maybe) before applying viewmodellag feature.

**Comment by DrAbcOfficial** [comment]
there did is a cvar `cl_modellag_autostop` to do it
when your fov is differ to `default_fov`, it will stop applying viewmodelag

**Comment by marvinmods** [comment]
> there did is a cvar `cl_modellag_autostop` to do it
> 
> when your fov is different to `default_fov`, it will stop applying viewmodelag

this only works if default_fov is exactly 90

**Comment by DrAbcOfficial** [comment]
tested, works fine to me, If you are talking about modellag stopping when fov is set to 120, that is because svencoop's fov is limited to 0~110
a number clamp added in 0042597, you can grab livebuild in github action

**Comment by DrAbcOfficial** [comment]
> it works yeah, but now weapon changing is bugged when `cl_hud_csgo` is 1

10c2f64

**Comment by marvinmods** [comment]
You should probably also do this for cl_crosshairautohide
