### ISSUE TITLE
[Feature] Camera bone animation like Half-Life: MMOD 

### ISSUE THREAD

**Issue by svcino** [DrAbcOfficial/ABCEnchance#26]
https://github.com/DrAbcOfficial/ABCEnchance/assets/33147204/dbe1bc55-934e-44ae-9f6a-e4e0c0a68f27

cl_vm_cam_anim 0-1
cl_vm_cam_anim_bone 0-256

**Comment by GAYd0N** [comment]
fork了只会改readme的杂鱼~

**Comment by GAYd0N** [comment]
> 2023-07-23.16-43-57.mp4 
> cl_vm_cam_anim 0-1 cl_vm_cam_anim_bone 0-256

fork了只会改readme的杂鱼~

**Comment by hzqst** [comment]
<img width="718" alt="image" src="https://github.com/DrAbcOfficial/ABCEnchance/assets/12287588/5d1b35fc-1881-4594-bf4c-8c3c04135f94">

invalid issue

**Comment by svcino** [comment]
Closed and invaild.
