### ISSUE TITLE
未能正常进入游戏

### ISSUE THREAD

**Issue by 7UMENGL1aNG** [DrAbcOfficial/ABCEnchance#32]
![image](https://github.com/DrAbcOfficial/ABCEnchance/assets/97338615/380f7ddb-9e3a-4c31-a794-c9686edc4578)
在装上Metahook和ABCEnchance后出现如上图情况，将ABCEnchance.dll从插件列表里移除后能正常打开，故推测为该插件问题。

安装的过程：
首先安装Metahook，利用其文件的"install-to-SvenCoop.bat"的一键安装，自动弹出插件列表，在第一行写入"ABCEnchance.dll"。
此后将abcenchance文件夹复制到目录steamapps\common\Sven Co-op\svencoop下，将ABCEnchance.dll复制到目录steamapps\common\Sven Co-op\svencoop\metahook\plugins下，将vpx.dll复制到目录steamapps\common\Sven Co-op下。（看了好几遍应该是和readme一样的）

打开游戏的过程：
从Steam打开Sven Co-op，进入游戏后黑屏，可以点击一些按钮，但在尝试连接服务器 或者 退出游戏时，将进行报错。

目录下出现mdmp为后缀的报错文件，不清楚其是否对debug有用，暂不上传。

**Comment by 7UMENGL1aNG** [comment]
在奇奇怪怪的情况下解决了黑屏问题，我根本不知道这样做为啥能解决这个问题。

解法：
分别下载新、老版本的metahook，新、老版本的ABCEnhance，
在各种新老版本配合下尝试进入游戏(新metahook，老ABCEnhance；老meathook，老ABCEnhance；老metahook，新ABCEnhance等排列组合)
最后似乎在新版本metahook，老版本ABCEnhance进入游戏，主界面黑屏，但加入服务器时未报错，再退出到主页面后，动画正常加载了。
再将新版本ABCEnhance替换，进入游戏，正常游玩。

（等等去尝试重启，看看能否保持正常）

**Comment by GAYd0N** [comment]
用的什么版本，有时候更新的源码是未完成的，Action里最新的build不一定能用

**Comment by 7UMENGL1aNG** [comment]
> 用的什么版本，有时候更新的源码是未完成的，Action里最新的build不一定能用

所谓的最新版，是：
Metahook v20230901a （五天前看的时候大概是2weeks ago）
ABCEnhance v20230821（五天前看的时候是3weeks ago）

旧版即为各最新版本前的版本：
Metahook 大概是v20230729a
ABCEnhance 大概是v20230723

我个人觉得你的这个推测可能有误，更新的源码不太可能两三周都没完成吧？


值得一提的是：为了排除文件干扰我将所有游戏文件都删了重新下，不知为何，其中的font文件会始终保持被系统占用，哪怕我手动安装了之后也是；直到能正常游玩后，此时退出并删除ABCEnhance准备更新，发现确实能删除了。

目前运行良好，无法复现错误。
