### ISSUE TITLE
[BUG]设置菜单出错

### ISSUE THREAD

**Issue by 7UMENGL1aNG** [DrAbcOfficial/ABCEnchance#33]
使用目前最新版metahook (v20230919b) 和 最新版ABCEnhance (v20230921)进行测试。
在主界面点击"设置-音频"及"设置-视频"中"高级..."选项，会导致菜单出错。
![image](https://github.com/DrAbcOfficial/ABCEnchance/assets/97338615/38df2b6e-1afd-4cb6-bf6f-42bcc2f514c9)

**Comment by DrAbcOfficial** [comment]
无解，等我有时间重新写个设置菜单
