### ISSUE TITLE
[BUG]计分栏偶尔会丢失某些人信息

### ISSUE THREAD

**Issue by 7UMENGL1aNG** [DrAbcOfficial/ABCEnchance#34]
![2082ffb74f96543f212efec138a3dc44](https://github.com/DrAbcOfficial/ABCEnchance/assets/97338615/4e07ea77-7f02-4647-b311-4c75ebe2c54c)
上图图一，玩家信息(Robo Grunt)未进入计分板中

![6a44f689e9635613623f42b1c1b4e44f](https://github.com/DrAbcOfficial/ABCEnchance/assets/97338615/04cc0b66-eec2-4cf3-9421-0457018ae94d)
上图图而，玩家信息(暮光闪闪)未进入计分板中

这是很早就有的问题了。长时间观察下来触发条件依然不明。
测试服务器为：Null真伤服

**Comment by 7UMENGL1aNG** [comment]
解决这个问题的顺便可以考虑把服务器管理员的标志加上，就是那个银色金色的扳手符号。

**Comment by GAYd0N** [comment]
> 解决这个问题的顺便可以考虑把服务器管理员的标志加上，就是那个银色金色的扳手符号。

其实是有的就是不太明显，对应的管理员头像会有银色金色的边框

**Comment by DrAbcOfficial** [comment]
可能在 fbfaaf839ec0e0ec534c6afe7d9c30306068b214 里修复了
