### ISSUE TITLE
[BUG]侧边栏的文字显示不完全

### ISSUE THREAD

**Issue by 7UMENGL1aNG** [DrAbcOfficial/ABCEnchance#37]
![image](https://github.com/DrAbcOfficial/ABCEnchance/assets/97338615/18da9770-c6a9-409a-8bc1-c1b82ec7226f)
首先说明，**cl_sideenable 0/1** 已尝试过，无用
在Null真伤服使用"fireworks"指令会出现这样的情况，在老梦的经验服加点也会出现这样的情况。

**Comment by GAYd0N** [comment]
首先说明，cl_sideenable 0/1 与此无关，那个是在左边显示金钱/速度的
