### ISSUE TITLE
cl_crosshairautohide 1 缩放不会自动隐藏动态准星

### ISSUE THREAD

**Issue by NoobLCH** [DrAbcOfficial/ABCEnchance#42]
如标题，在cl_crosshairautohide 1时，使用能开镜的武器在开镜时动态准星仍旧存在。

**Comment by 7UMENGL1aNG** [comment]
#39 于三天前已被关闭，似乎已解决

**Comment by NoobLCH** [comment]
> 似乎与#39产生原因相同，于三天前已被关闭。

否，那是cl_crosshair 0/1可以正常关闭/开启动态准星
但是cl_crosshairautohide仍旧not working。
以前可用的版本里在cl_crosshair 1启动动态准星后，若开启cl_crosshairautohide 1，能缩放的武器在缩放时会自动把动态准星隐藏；而现在cl_crosshairautohide 1后武器缩放不会隐藏动态准星

**Comment by 7UMENGL1aNG** [comment]
> > 似乎与#39产生原因相同，于三天前已被关闭。
> 
> 否，那是cl_crosshair 0/1可以正常关闭/开启动态准星 但是cl_crosshairautohide仍旧not working。 以前可用的版本里在cl_crosshair 1启动动态准星后，若开启cl_crosshairautohide 1，能缩放的武器在缩放时会自动把动态准星隐藏；而现在cl_crosshairautohide 1后武器缩放不会隐藏动态准星

猜想之一：如果连cl_crosshair都无法控制动态准星的关闭，是不是在某种意义上代表动态准星是常显，既然常显，那么用cl_crosshairautohide1 并开启缩放和cl_crosshair 1没用；它自始至终就在那里，用任何手段都没法使其关闭。
