### ISSUE TITLE
[避免误导]调整cl_sideenable配置介绍

### ISSUE THREAD

**Issue by 7UMENGL1aNG** [DrAbcOfficial/ABCEnchance#45]
https://github.com/DrAbcOfficial/ABCEnchance/issues/37#issuecomment-1840510269
正如他所述，可以考虑调整为"**开启左侧边栏金钱/速度显示**"
如果有其他更鲜明且无误导的文字，那更好。

**Comment by DrAbcOfficial** [comment]
d18546cde4f31b14a36a1a0c0a9fabdb1c201b00

**Comment by 7UMENGL1aNG** [comment]
> 没搞懂， #37 修好了不close就算了，还单开一个帖子, 那为什么不直接在原帖里回复？

很简单，因为我没上线测试过，如果你觉得已经修好了可以@我提醒我关掉，亦或者提醒库主人自行关闭。
正如Abc先生两天前所做的那样。
