### ISSUE TITLE
How to disable CS hud leaving only the radar?

### ISSUE THREAD

**Issue by DarkenXD** [DrAbcOfficial/ABCEnchance#77]
Cant use cl_hud_csgo 0

**Comment by DrAbcOfficial** [comment]
Replace `svencoop/abcenchance/res` with the file in `svencoop/abcenchance/res_vanilliaLike`
Since Sven Co-op does not intend to implement the Addictive and Blur rendering modes of the HL25 VGUI2, a full restoration of the original interface using VGUI is not possible

**Comment by DarkenXD** [comment]
Ok tried to change it to res_vanillalike and got this result
![изображение](https://github.com/user-attachments/assets/2a11fbda-b551-4fa3-b3ba-07b89ad9d80b)

**Comment by DrAbcOfficial** [comment]
you copy files in `svencoop/abcenchance/res_vanilliaLike`
you paste files to `svencoop/abcenchance/res`

**Comment by DarkenXD** [comment]
thank you
